import fumen from "./fumen.js";
import gfycat from "./gfycat.js";
import image from "./image.js";
import imgur from "./imgur.js";
import soundcloud from "./soundcloud.js";
import twitch from "./twitch.js";
import video from "./video.js";
import youtube from "./youtube.js";
import channel9 from "./channel9.js";
export default [fumen,gfycat,image,imgur,soundcloud,twitch,video,youtube,channel9];